services:
  client:
    container_name: frontend
    build: ./client
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: npm start
    volumes:
      - ./client:/usr/src/app
  server:
    container_name: backend
    build: ./server
    ports:
      - 4000:4000
    stdin_open: true
    environment:
      - NODE_ENV=development
    command: nodemon index.js
    volumes:
      - ./server:/usr/src/app
  db:
    container_name: database
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=.c.6"#?{L}cTr~P(